palette = "catppuccin_mocha"
command_timeout = 3000

[username]
format = "[$user]($style)@"
show_always = true
style_root = "bold red"
style_user = "bold blue"

[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = false
style = "dimmed lavender"
trim_at = "-"

[directory]
style = "mauve"
read_only = " ï ½"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "repo:/"
home_symbol = "~"

[sudo]
disabled = false
style = "bold red"
symbol = "ïŸ› "

[git_branch]
symbol = "ï˜ "
style = "bold lavender"

[git_status]
style = "dimmed sky"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡• â‡¡${ahead_count} â‡£${behind_count}"
deleted = "âœ–"
modified = "âœ±"
staged = "â—"
untracked = "â€¦"

[cmd_duration]
disabled = false
min_time = 500
format = "took [$duration]($style)"
style = "bold peach"

[battery]
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"
full_symbol = "ï•¸"

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold peach"

[[battery.display]]
threshold = 80
style = "bold green"

[time]
disabled = true
format = "ğŸ•’ [$time]($style)"
style = "dimmed subtext1"
time_format = "%H:%M:%S"

[character]
error_symbol = "[â¯](red)"
success_symbol = "[â¯](blue)"

[status]
disabled = false
format = '[\[$symbol$status\]]($style) '
symbol = "âœ–"
style = "bold red"
map_symbol = true
pipestatus = true

# Language & Runtime Symbols
[aws]
symbol = "ïµ "
[conda]
symbol = "ï„Œ "
[dart]
symbol = "îš“ "
[docker_context]
symbol = "ïŒˆ "
style = "blue"
[elixir]
symbol = "î‰µ "
[elm]
symbol = "î˜¬ "
[golang]
symbol = "î "
[hg_branch]
symbol = "ï˜ "
[java]
symbol = "ï“¤ "
[julia]
symbol = "î˜¤ "
[nim]
symbol = "ïš¤ "
[nix_shell]
symbol = "ï‹œ "
[nodejs]
symbol = "îœ˜ "
style = "green"
[package]
symbol = "ï‘¦ "
[perl]
symbol = "î© "
[php]
symbol = "ï‘— "
[python]
symbol = "îˆµ "
style = "yellow"
[ruby]
symbol = "îˆ¾ "
[rust]
symbol = "î¨ "
style = "red"
[swift]
symbol = "ï£¡ "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
